export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const EMPTY_CART="EMPTY_CART"
export const PRODUCT_LIST="PRODUCT_LIST"
export const PLAYER_LIST="PRODUCT_LIST"
export const TEAM_LIST="TEAM_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"
export const SET_TEAM_LIST="SET_TEAM_LIST"
export const UPDATE_TEAM_PLAYERS="UPDATE_TEAM_PLAYERS"
export const SET_PLAYER_LIST="SET_PLAYER_LIST"
export const SEARCH_PRODUCT="SEARCH_PRODUCT"
export const PLAYER_SOLD="PLAYER_SOLD"




